### ISSUE TITLE
<local_delivery_cost> устарел. Вместо него нужно использовать <delivery-options>

### ISSUE THREAD

**Issue by RusNimex** [pastuhov/yii2-yml-catalog#14]
В [документации](https://yandex.ru/support/partnermarket/elements/delivery-options.xml) пишут об этом: 

> Элемент local_delivery_cost является устаревшим. Рекомендуем отказаться от использования данного элемента и перейти на использование элемента delivery-options, так как новый элемент предоставляет больше возможностей.

Теперь можно указывать несколько типов доставок `<option>`: 
- атрибут cost — стоимость доставки в рублях;
-  атрибут days — срок доставки в рабочих днях;
-  атрибут order-before (необязательный) — время оформления заказа, до наступления которого действуют указанные сроки и условия доставки.

Элемент <delivery-options> может содержать до пяти элементов <option> для указания разных типов и условий доставки (например, обычная, экспресс и т. п.).

**Comment by pastuhov** [comment]
Частично реализовано
