### ISSUE TITLE
Ошибка: Text file busy. Происходит во время перемещения файла в $publicPath

### ISSUE THREAD

**Issue by RusNimex** [pastuhov/yii2-yml-catalog#17]
Во время [перемещения файла](https://github.com/pastuhov/yii2-yml-catalog/blob/master/src/actions/GenerateAction.php#L124) происходит ошибка:  Text file busy

**Comment by pastuhov** [comment]
Нужно больше инфы, есть trace? 
Спасибо!

**Comment by RusNimex** [comment]
Возможно этот trace будет информативен:

> 2016-08-23 11:57:12 [10.0.2.2][1][4229p8osio6p89rbegih7asfj0][error][yii\base\ErrorException:2] yii\base\ErrorException: rename(/var/www/project/data/app/backend/runtime/yml-test.xml,/var/www/project/data/app/frontend/web/yml/yml-test.xml): Text file busy in /var/www/project/data/app/vendor/pastuhov/yii2-yml-catalog/src/actions/GenerateAction.php:124
> Stack trace:
> #0 /var/www/project/data/app/vendor/yiisoft/yii2/base/Action.php(92): pastuhov\ymlcatalog\actions\GenerateAction->run()
> #1 /var/www/project/data/app/vendor/yiisoft/yii2/base/Action.php(92): ::call_user_func_array:{/var/www/project/data/app/vendor/yiisoft/yii2/base/Action.php:92}('???', '???')
> #2 /var/www/project/data/app/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams('???')
> #3 /var/www/project/data/app/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('???', '???')
> #4 /var/www/project/data/app/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('???', '???')
> #5 /var/www/project/data/app/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest('???')
> #6 /var/www/project/data/app/backend/web/index.php(18): yii\base\Application->run()

Чем еще могу помочь? Использую PHP 7.0.1.

**Comment by pastuhov** [comment]
Проявляется под вагрантом или virtualbox?
Без виртуализации и на продакшене не проявляется

**Comment by RusNimex** [comment]
под вагрантом

**Comment by RusNimex** [comment]
Если использовать `copy()` вместо `rename()`, то генерация yml стабильна.

**Comment by RusNimex** [comment]
Извиняюсь, вызывал action из yii\web\Controller, а не из yii\console\Controller. При вызове action консольно все работает стабильно, нет никаких проблем.
