### ISSUE TITLE
Как вывести keywords?

### ISSUE THREAD

**Issue by Sirgalas** [pastuhov/yii2-yml-catalog#26]
появилась необходимость вывети keywords. Вопрос мне наследоваться от ваших моделей и интерфейсов и добавлять или у вас есть возможность вывести keywords штатными средствами?

**Comment by pastuhov** [comment]
не могу найти keywords в документации к yml https://yandex.ru/support/partnermarket/yml/about-yml.xml

**Comment by Sirgalas** [comment]
У меня просит заказчик добавить keywords она использует yml как на маркете так и на prom.ua который требует наличие keywords. Но я и не говорил что есть в документации яндекса. Спросил есть ли возможность вненсения дополнительных полей в создаваемый вамим приложением yml штатными средствами или необходимо наследоваться и создавать самому? И если я отнаследуюсь они выведутся или надо будет что то подключать?

**Comment by pastuhov** [comment]
Есть возможность подсунуть свой класс Offer

```
            'offerClasses' => [
                'sirgalas\MyOffer'
            ],
```

Свой класс можно отнаследовать от 'pastuhov\ymlcatalog\models\SimpleOffer'

**Comment by Sirgalas** [comment]
Спасибо

**Comment by pastuhov** [comment]
welcome
