### ISSUE TITLE
Добавление поля

### ISSUE THREAD

**Issue by mrfinrod** [pastuhov/yii2-yml-catalog#27]
Создал свой оффер-класс. Нужно вывести название модели. Делаю так:`public function getGoodModel()
    {
        return $this->attributes['good_model'];
    }`
Не могу понять, где вызывать этот метод, чтобы good_model попала в yml-файл?

**Comment by pastuhov** [comment]
для того чтобы изменить вывод в yml нужно переопределить $tagProperties (если нужно вмешаться в св-ва тега offer) или getYmlAttributes() (если нужно добавить новый тэг внутрь <offer>)

**Comment by mrfinrod** [comment]
Спасибо. Пришлось переопределить аж 3 класса: YmlCatalog, GenerateAction и сам оффер. Но зато теперь можно легко добавлять любые поля

**Comment by pastuhov** [comment]
Может быть сделаете pull request?
