### ISSUE TITLE
Rename function do not work under Windows

### ISSUE THREAD

**Issue by uranum** [pastuhov/yii2-yml-catalog#28]
Функция rename() выдает ошибку (OpenServer 5.2.6): 
`PHP Warning 'yii\base\ErrorException' with message 'rename(W:\domains\site\console\runtime/yml.xml,W:\domains\site\frontend/yml.xml): ╧ЁюЎхёё эх ьюцхЄ яюыєўшЄ№ фюёЄєя ъ Їрщыє, Єръ ъръ ¤ЄюЄ Їрщы чрэ Є фЁєушь яЁюЎхёёюь. (code: 32)'`
Если параметры передать строкой - все работает, если через алиасы - ошибка.

Ну и enableGzip не работает под Windows - команда cat отсутствует.

**Comment by pastuhov** [comment]
К сожалению не планируется поддержка платформы win. Попробуйте ubuntu или debian :)
