### ISSUE TITLE
Ошибка DeliveryOptions

### ISSUE THREAD

**Issue by averinbox** [pastuhov/yii2-yml-catalog#30]
Делаю как в примере опцию "delivery-options".
```
public function getDeliveryOptions() {
$result = [];
$options = [
            'cost' => 0,
            'days' => '15-30'
        ];
$deliveryOption = new DeliveryOption();
$deliveryOption->cost = $options['cost'];
$deliveryOption->days = $options['days'];
$result[] = $deliveryOption;
return $result;
}
```
При генерации файла получаю: Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: pastuhov\ymlcatalog\models\DeliveryOption::getCost()'

Заглянул в класс и вправду в модели DeliveryOption нет такого статического метода getCost().
Может что не так делаю? Остальное всё работает без проблем, опция данная нужна.

**Comment by averinbox** [comment]
Решил созданием наследованием класса и имплиментом от DeliveryOptionInterface

**Comment by pastuhov** [comment]
Да, интерфейс реализован только в тестах
