### ISSUE TITLE
Добавлена поддержка всех возможностей последней версии Яндекс Маркет

### ISSUE THREAD

**Issue by execut** [pastuhov/yii2-yml-catalog#36]
Здравствуйте! Обновил компонент до поддержки последней версии Маркета в своей ветке https://github.com/execut/yii2-yml-catalog/tree/update-yml-version
Всё сделал, только, к сожалению, в последнюю очередь заметил тесты=( Нужно было через них дорабатывать. Пока нет времени их привести к полному покрытию. Думаю нужно их перевести на codeception. Планирую добавить действие для возможности скачивания файла Яндексом через логин\пароль. Решил уведомить вас об этом, чтобы не делать двойную работу. Возможно мои изменения сойдут и для master, либо у вас найдётся время допилить тесты.

Среди добавленных возможностей:
1. Более точная валидация всех данных по документации яндекса.
2. Возможность указывать валюту не только через ActiveRecord, но и через объект.
3. Все общие элементы между SimpleOffer и CustomOffer вынесены в Offer как в интерфейсе так и в модели
4. Добавлена возможность указывать все возможные параметры Маркета, среди новых в Offer это:
* recValues
* group_id
* downloadable
* dimensionsValues
* weight
* expiry
* params
* stepQuantity
* minQuantity
* outlets
в CustomOffer:
* model
* vendorCode
* typePrefix
* type
в SimpleOffer:
* name
* model
* vendor
* vendorCode
в DeliveryOption
* orderBefore

**Comment by pastuhov** [comment]
Добрый день!

Спасибо! Посмотрим что можно сделать.
По поводу codecepton - замечательный фреймворк, но его плюсы здесь не будут востребованы скорее всего, только overhead достанется. Phpunit простой и быстрый.

**Comment by execut** [comment]
Продолжаю работу. Хочу сделать на этой неделе это:
1. Покрыть новый функционал тестами на phpUnit
2. Добавить инструментарий для работы со справочником категорий Яндекс Маркета
3. Сделать action для скачивания файлов через авторизацию Яндексом самостоятельно
4. Символы ", &, >, <, ' везде заменять на эквивалентные html-коды
На потом:
* Сделать валидацию непечатаемых символов, поскольку Яндекс их не допускает (https://yandex.ru/support/partnermarket/yml/about-yml.html)
* Поддержка price from="true"
* Поддержка age
* Поддержка нескольких barcode
* Поддержка в expiry формата вида P1Y2M10DT2H30M
* Генерация прайса в несколько процессов(потоков) для сокращения времени генерации.

Есть замечания по текущим наработкам?

**Comment by pastuhov** [comment]
Планы крутые :) 
Замечаний нет, есть просьба - разбить это все на куски (отдельные ветки), отдельными пулреквестами пропихивать в мастер. Так ревьюверам не будет страшно и самому понятнее, код лучше.

**Comment by execut** [comment]
Думаю сделать работу с категориями в отдельном пакете\модуле. Будут миграции, контроллеры, возможно даже круд для работы с ними и поиска через ajax из других крудов, а зависимости вашего компонента от нового нет никакой, всё идёт за интерфейсом Offer в методе getCategory и реализации CategoryInterface.

**Comment by execut** [comment]
С отдельным модулем решил отложить. В итоге всё запланированное сделал в 4-ех pull-запросах.
