### ISSUE TITLE
Не проходит валидацию market_Category

### ISSUE THREAD

**Issue by carono** [pastuhov/yii2-yml-catalog#49]
Сгенерированный файл не проходит валидацию на яндексе из-за тега `market_Category`, т.к. он ожидает в нижнем регистре `market_category`

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
<yml_catalog date="2017-09-26 20:10">
    <shop>
        <name>Магазин</name>
        <company>ООО Рога и Копыта</company>
        <url>http://shop.site</url>
        <cpa>0</cpa>

        <currencies>
            <currency id="RUR" rate="CBRF" plus="0"/>
        </currencies>
        <categories>
            <category id="545" parentId="543">Кашемир 100%</category>
        </categories>
        <offers>
            <offer id="2098" available="true">
                <url>http://shop.site/catalog/goods.html</url>
                <price>5760</price>
                <currencyId>RUR</currencyId>
                <categoryId>545</categoryId>
                <market_Category>Детские товары/Обучение и творчество/Хобби и творчество/Вязание</market_Category>
                <store>false</store>
                <delivery>true</delivery>
                <name>Кашемир 100%, светло-серый</name>
                <description></description>
                <cpa></cpa>
                <picture>
                    http://shop.site/image/img1.jpg
                </picture>
            </offer>
        </offers>
    </shop>
</yml_catalog>
```

Invalid content was found starting with element 'market_Category'. One of '{url, buyurl, price, oldprice, wprice, currencyId, xCategory, categoryId, `market_category`, picture, store, pickup, delivery, deliveryIncluded, local_delivery_cost, orderingTime, typePrefix, vendor, vendorCode, provider, tarifplan, model, author, name, publisher, series, year, ISBN, volume, part, language, binding, page_extent, table_of_contents, performed_by, performance_type, storage, format, recording_length, artist, title, media, starring, director, originalName, country, worldRegion, region, days, dataTour, hotel_stars, room, meal, included, transport, price_min, price_max, options, place, hall, hall_part, date, is_premiere, is_kids, aliases, additional, description, sales_notes, promo, manufacturer_warranty, seller_warranty, country_of_origin, downloadable, adult, age, barcode, cpa, fee, rec, expiry, weight, dimensions, param, related_offer, delivery-options, pricelabs_param, purchase_price}' is expected.

Я что-то делаю неверно?

**Comment by execut** [comment]
Этот тег используется в старой версии yml. В новой ставится только categoryId, который указывает на идентификатор категории. Если нужно категории Яндекса, то их нужно прогрузить отдельно через интерфейс Category, а из товара через categoryId указать на неё. В своём форке я сделал поддержку новой версии yml и функционал для работы с категориями яндекса, там в документации всё описано: https://github.com/execut/yii2-yml-catalog/tree/production
